https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

In [2]:
import numpy as np

x = np.array(range(10))

print(x)

[0 1 2 3 4 5 6 7 8 9]


# Basic slicing 

## start:stop:step 
<br>
--> x[start], x[start + 1*step], x[start + 2*step], ..., x[start + m*step]
start + m*step < stop < start + (m+1)*step

In [3]:
y = x[0:6:2]
print (y)

[0 2 4]


In [4]:
y = x[2:6:2]
print (y)

[2 4]


## start, stop, step < 0

x&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<br>
index>0  :&nbsp;   &nbsp;0&nbsp;  &nbsp;1&nbsp;  &nbsp;&nbsp;2&nbsp;&nbsp;3&nbsp;  &nbsp;4&nbsp;  &nbsp;5&nbsp;  &nbsp;6&nbsp;  &nbsp;7&nbsp;  &nbsp;8&nbsp;  9
<br>
index<0  :&nbsp; -10 -9 -8 -7 -6 -5 -4 -3 -2 -1
<br>
step>0   :   start ---> stop
<br>
step<0   :    stop <--- start

In [10]:
y = x[-1:1:-1]
print (y)

y = x[-7:9]
print (y)

[9 8 7 6 5 4 3 2]
[3 4 5 6 7 8]


## ::, : select all indices

In [11]:
y = x[2:]
print (y)

[2 3 4 5 6 7 8 9]


## Multidimension

In [12]:
y = x.reshape((2,5,1))
print (y)

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]


In [15]:
z = y[0:]
print (z)

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]


In [16]:
z = y[1:]
print(z)

[[[5]
  [6]
  [7]
  [8]
  [9]]]


In [18]:
z = y[0:1]
print (z)

[[[0]
  [1]
  [2]
  [3]
  [4]]]


In [19]:
z = y[-1]
print (z)

[[5]
 [6]
 [7]
 [8]
 [9]]


In [20]:
y = x.reshape((5,2,1))
print (y)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]

 [[8]
  [9]]]


In [21]:
z = y[1:4:2]
print(z)

[[[2]
  [3]]

 [[6]
  [7]]]


# Advanced indexing
## Integer array indexing


In [23]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = x[[0, 1, 2], [0, 1, 0]]
print (y)

[1 5 7]


**Explanation**:

[0, 1, 2] : row 0, row 1, row 2
<br> [0, 1, 0] : row 0 pick column 0 --> 1
<br> row 1 pick column 1 --> 4
<br> row 2 pick column 0 --> 7

In [24]:
y = x[[[0,0], [1,1], [2,2]], [[0,1],[1,2],[0,2]]]
print (y)

[[1 2]
 [5 6]
 [7 9]]


## Broadcast

In [25]:
y = x[[[0], [1], [2]], [[0,1],[1,2],[0,2]]]
print (y)

[[1 2]
 [5 6]
 [7 9]]


## np.newaxis
This will be error in broadcast

In [41]:
rows = np.array([0, 1, 2])
print (rows.shape)
y = x[rows, [[0,1],[1,2],[0,2]]]
print (y)

(3,)


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (3,2) 

In [42]:
rows = np.array([0, 1, 2])
rows = rows[:,np.newaxis] 
print (rows.shape)
#now broadcast can be applied
y = x[rows, [[0,1],[1,2],[0,2]]]
print (y)

(3, 1)
[[1 2]
 [5 6]
 [7 9]]


## np.ix_
There will be error in broadcast

In [44]:
rows = np.array([0, 1, 2])
columns = np.array([0,1])
y = x[rows, columns]
print (y)

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [45]:
rows = np.array([0, 1, 2])
columns = np.array([0,1])
y = x[np.ix_(rows, columns)]
print (y)

[[1 2]
 [4 5]
 [7 8]]
