Somes clarifications on performing tf.matmul, on reshaping a matrix and tf.matmul a matrix and its transposed matrix

In [2]:
import tensorflow as tf

In [5]:
# create a 2x2 rank 2 tensor (i.e matrix)
tensor_A = tf.constant([[0, 1], [1, 2]], name="A", dtype=tf.float32)

# print a tensor
print("A : \n{}".format(tensor_A))

A : 
[[0. 1.]
 [1. 2.]]


In [6]:
# create another 2x2 rank2 tensor
tensor_B = tf.constant([[1, 2], [2, 3]], name="B", dtype=tf.float32)

# print a tensor
print("B : \n{}".format(tensor_B))

B : 
[[1. 2.]
 [2. 3.]]


In [7]:
# see matmul
tensor_matmul = tf.matmul(tensor_A, tensor_B)
print("tensor_matmul : \n{}".format(tensor_matmul))

tensor_matmul : 
[[2. 3.]
 [5. 8.]]


So tf.matmul is dot product

In [8]:
# see multiply
tensor_multiply = tf.multiply(tensor_A, tensor_B)
print("tensor_multiply : \n{}".format(tensor_multiply))

tensor_multiply : 
[[0. 2.]
 [2. 6.]]


So tf.multiply is elementwise multiplication

In [10]:
# create a 2x3 matrix
C = tf.constant([[0, 0, 1], [1, 2, 3]], name="C", dtype=tf.float32)
print("C : \n{}".format(C))

C : 
[[0. 0. 1.]
 [1. 2. 3.]]


In [11]:
# transpose a matrix
C_t = tf.transpose(C)
print("C_t : \n{}".format(C_t))

C_t : 
[[0. 1.]
 [0. 2.]
 [1. 3.]]


In [12]:
# see tf.matmul
tensor_matmul = tf.matmul(C_t, C)
print("tensor_matmul : \n{}".format(tensor_matmul))

tensor_matmul : 
[[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 3.  6. 10.]]


In [16]:
# random (2, 3, 4) tensor
H, W, C = 2, 3, 5
shape = (H, W, C)
D = tf.random.uniform(shape, minval=0, maxval=5, dtype=tf.int32, seed=None, name="D")
print("D : \n{}".format(D))

D : 
[[[4 2 2 0 0]
  [2 3 1 4 1]
  [4 3 0 3 4]]

 [[0 1 3 0 2]
  [1 1 2 1 4]
  [0 1 3 2 3]]]


In [21]:
# reshape 1
D_reshape1 = tf.reshape(D, (C, H*W))
print("D_reshape1 : \n{}".format(D_reshape))

D_rs1_t = tf.transpose(D_reshape1)
print("D_rs1_t : \n{}".format(D_rs1_t))

matmul1 = tf.matmul(D_reshape1, D_rs1_t)
print("matmul1 : \n{}".format(matmul1))


D_reshape1 : 
[[4 2 2 0 0 2]
 [3 1 4 1 4 3]
 [0 3 4 0 1 3]
 [0 2 1 1 2 1]
 [4 0 1 3 2 3]]
D_rs1_t : 
[[4 3 0 0 4]
 [2 1 3 2 0]
 [2 4 4 1 1]
 [0 1 0 1 3]
 [0 4 1 2 2]
 [2 3 3 1 3]]
matmul1 : 
[[28 28 20  8 24]
 [28 52 32 18 36]
 [20 32 35 15 15]
 [ 8 18 15 11 11]
 [24 36 15 11 39]]


In [23]:
# reshape 2
D_reshape2 = tf.reshape(D, (H*W, C))
print("D_reshape2 : \n{}".format(D_reshape2))

D_rs2_t = tf.transpose(D_reshape2)
print("D_rs2_t : \n{}".format(D_rs2_t))

matmul2 = tf.matmul(D_rs2_t, D_reshape2)
print("matmul2 : \n{}".format(matmul2))

D_reshape2 : 
[[4 2 2 0 0]
 [2 3 1 4 1]
 [4 3 0 3 4]
 [0 1 3 0 2]
 [1 1 2 1 4]
 [0 1 3 2 3]]
D_rs2_t : 
[[4 2 4 0 1 0]
 [2 3 3 1 1 1]
 [2 1 0 3 2 3]
 [0 4 3 0 1 2]
 [0 1 4 2 4 3]]
matmul2 : 
[[37 27 12 21 22]
 [27 25 15 24 24]
 [12 15 27 12 24]
 [21 24 12 30 26]
 [22 24 24 26 46]]
